server, fix errors when changing language
Fix errors when changing language
("qrc:/gcompris/src/server/activities/LineReport.qml:157:
TypeError: Value is null and could not be converted to an object")

To prevent similar errors, add a isReady bool in Master, set it to false before
all activityModel loading/update, and true when loading is complete. And use
that in bindings in LineReport to avoid such errors while activityModel is loading.